language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ucpfis' ]; then cd .. && eval "mv $currentfolder generator-ucpfis" && cd generator-ucpfis; fi

